//go:build ignore
// +build ignore

// Bundles the ZPLkit library modules into single-file builds under zplkit/dist/
// for embedding in other tools. Run from the repository root:
//
//	go run tools/bundle-lib.go
//
// Emits two variants (see variants below): a "full" build with everything and
// a "lite" build that drops the modules most consumers of a ZPL library don't
// need, at roughly 40% of the transfer size.
//
// This is plain ordered concatenation, not a real bundler, and deliberately
// so: every module is already a self-contained IIFE that attaches itself to
// globalThis (and zplkit.js, appended last, also sets module.exports for
// CommonJS consumers), so nothing needs rewriting or wrapping. That keeps the
// output readable/debuggable and keeps the project free of an npm toolchain.
//
// No minification for the same reason - it would mean vendoring a JS minifier
// with nothing else in the project needing one. Production hosts can compress
// the generated JavaScript at the HTTP layer.
//
// The build tag above keeps this file out of `go build .` for the server.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Load order matters: zpl-parser.js and zpl-generator.js read global.ZPLModel
// at load time (not lazily), so zpl-model.js has to come first. This mirrors
// the <script> order in studio/index.html - keep the two in sync when adding
// a module. studio/app.js is intentionally absent: it is the Studio UI, not library
// code, and depends on the DOM.
//
// zplkit.js (the facade) is appended to every variant automatically and
// so is not listed here.
var (
	// The core: read ZPL, modify it, write it back out, plus the barcode
	// pattern encoders needed to draw a preview of what was parsed.
	coreModules = []string{
		"zplkit/zpl-model.js",
		"zplkit/zpl-parser.js",
		"zplkit/zpl-generator.js",
		"zplkit/barcodes.js",
	}
	// Everything else. Omitting these is safe rather than merely untested:
	// the parser/generator reach for ZPLGraphic only behind
	// `global.ZPLGraphic &&` guards, so without gfa-codec/inflate an
	// embedded graphic round-trips as verbatim raw text instead of being
	// decoded - it is never silently dropped and nothing throws.
	extraModules = []string{
		"zplkit/inflate.js",        // DEFLATE/zlib - only needed by gfa-codec + xlsx
		"zplkit/gfa-codec.js",      // ^GF/~DG graphics
		"zplkit/image-mono.js",     // RGBA -> 1bpp, only useful with graphics
		"zplkit/zpl-diff.js",       // compare two labels
		"zplkit/zpl-glossary.js",   // German command explanations (biggest single module, pure text)
		"zplkit/csv-parser.js",     // mail-merge data sources
		"zplkit/xlsx-parser.js",    //   "
		"zplkit/label-sheets.js",   // A4 sheet geometry
		"zplkit/zpl-render.js",     // element geometry/sizing (needs a DOM canvas, browser-only)
		"zplkit/pdf-writer.js",     // single/multi-page PDF from JPEG or 1-bit raster bytes (no deps)
		"zplkit/gif-writer.js",     // static-image GIF89a encoder (no deps)
		"zplkit/backend-client.js", // optional print/label-server client (Go serves the Zebra subset when configured)
	}
	facade = "zplkit/zplkit.js"
)

type variant struct {
	out     string
	modules []string
	note    string
}

func variants() []variant {
	full := append(append([]string{}, coreModules...), extraModules...)
	return []variant{
		{
			out:     "zplkit/dist/zplkit-full.js",
			modules: full,
			note:    "Vollständig: Parser, Generator, Barcodes, Grafiken (^GF/~DG, Z64), Diff, Glossar, CSV/XLSX, Etikettenbögen, Element-Geometrie/Größenberechnung (ZPLRender - benötigt einen DOM-Canvas, browserseitig), PDF-/GIF-Export, optionale Backend-Schnittstelle (Drucken/Etikettenserver).",
		},
		{
			out:     "zplkit/dist/zplkit-lite.js",
			modules: coreModules,
			note:    "Schlank: nur Parser, Generator, Modell und Barcode-Encoder. Ohne Grafik-Codec, Glossar, Diff, CSV/XLSX, Etikettenbögen - eingebettete Grafiken werden unverändert durchgereicht statt dekodiert.",
		},
	}
}

func build(v variant) error {
	mods := append(append([]string{}, v.modules...), facade)

	var b strings.Builder
	fmt.Fprintf(&b, `/* ZPLkit - generated by tools/bundle-lib.go, do NOT edit by hand.
	   Source of truth is the individual modules under zplkit/ (see README.md).

   %s

	   Usage (browser):  <script src="%s"></script> then use window.ZPLkit
	   Usage (CommonJS): const ZPLkit = require('./%s');

   Bundled modules, in load order:
`, v.note, filepath.Base(v.out), filepath.Base(v.out))
	for _, m := range mods {
		fmt.Fprintf(&b, "     %s\n", m)
	}
	b.WriteString("*/\n")

	for _, m := range mods {
		data, err := os.ReadFile(filepath.FromSlash(m))
		if err != nil {
			return err
		}
		fmt.Fprintf(&b, "\n/* ===== %s ===== */\n", m)
		b.Write(data)
		// Each module ends in `})(...);` - a trailing newline keeps the next
		// module's opening paren off that same line, which would otherwise
		// parse as a call on the previous expression.
		if !strings.HasSuffix(string(data), "\n") {
			b.WriteString("\n")
		}
	}

	if err := os.MkdirAll(filepath.Dir(filepath.FromSlash(v.out)), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.FromSlash(v.out), []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("%-24s %2d Module, %6.1f KB\n", v.out, len(mods), float64(len(b.String()))/1024)
	return nil
}

func main() {
	for _, v := range variants() {
		if err := build(v); err != nil {
			fmt.Fprintf(os.Stderr, "bundle-lib: %v\n", err)
			os.Exit(1)
		}
	}
}
